[tasks."spinup:backend"]
alias       = "sb"
description = "Start database and API server"
depends     = ["spinup:db", "spinup:api"]

[tasks."spinup:db"]
description = "Start db container and check status, no cred setup"
depends     = ["db:up", "db:status-wait", "db:migrate"]

[tasks."spinup:api"]
description = "Start up API server and check status"
depends     = ["api:up", "api:status-wait"]
