[build-system]
requires      = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[project]
name    = "glia_core"
version = "0.1.0"
requires-python = ">=3.12.0"                                                       # Also listed in mise.toml and glia/pyproject.toml in [tool.ty] and [project]
